### ISSUE TITLE
Requires Go 1.17

### ISSUE THREAD

**Issue by stevenanthonyrevo** [sensepost/godoh#11]
Hello, 

Can you run the project with Go 1.13 instead of Go 1.17? 

I am receiving an error.

```
# golang.org/x/sys/unix
../../go/pkg/mod/golang.org/x/sys@v0.5.0/unix/syscall.go:83:16: undefined: unsafe.Slice
../../go/pkg/mod/golang.org/x/sys@v0.5.0/unix/syscall_darwin.go:95:8: undefined: unsafe.Slice
../../go/pkg/mod/golang.org/x/sys@v0.5.0/unix/syscall_unix.go:118:7: undefined: unsafe.Slice
../../go/pkg/mod/golang.org/x/sys@v0.5.0/unix/sysvshm_unix.go:33:7: undefined: unsafe.Slice
note: module requires Go 1.17
```

**Comment by leonjza** [comment]
Hey, not really no.

However, there are three options.

1) Try and compile an older commit where 1.13 might work.
2) Use the last release binaries (static key warning)
3) Compile somewhere else that has a newer go and copy the binaries from there.
