### ISSUE TITLE
server/agent not polling

### ISSUE THREAD

**Issue by ManjuLalwani** [sensepost/godoh#4]
My agent is stuck at INFO[0000] Starting polling...                           ident=80my4 module=agent

On the server C:\godoh\goDoH>godoh c2 -d mydomain.com
time="2020-05-11T12:47:36Z" level=info msg="Using `google` as preferred provider\n"
time="2020-05-11T12:47:36Z" level=info msg="Using mydomain.com as DNS domain\n"
Commands are directed to agents after switching to its context.

Use the `agents` command to list agents.
Use the `use agent-id` to interact with that agent and issue commands.
Use the `download path` in an agents' context to download files.
Use the `back` command to go back.

Current agent context: ``

c2> time="2020-05-11T12:47:36Z" level=info msg="DNS C2 starting..." domain=mydomain.com module=c2

c2> agents
No agents registered.

godoh test gives no errors

**Comment by leonjza** [comment]
Sure your agent has outbound communication?

**Comment by ManjuLalwani** [comment]
Yes Leon. The agent does have outbound communication. Also able to
successfully ssh in to the server.

When I run godoh on the server side , should I expect port 53 to be opened
up after that ? Though my domain resolution works fine from every where , I
do not see any port being opened up after I run godoh on the server side.
nmap scan from the agent to the server shows only port 22 opened.

On the agent side , tried packet capture with google as the provider-  see
my traffic going to dns.google.https ( 192.168.26.102 is my server )

[image: image.png]

06:00:04.654601 IP 192.168.26.65.47301 > dns.google.domain: 53677+ [1au]
PTR? 102.26.168.192.in-addr.arpa. (56)

06:00:04.659317 IP dns.google.domain > 192.168.26.65.47301: 53677 NXDomain
0/0/1 (56)

Then the agent is stuck at polling and I see nothing on the server side.

Please let me know if I am missing something on my side based on this
information.

Thanks,
Manju Lalwani

**Comment by leonjza** [comment]
> When I run godoh on the server side , should I expect port 53 to be opened up after that ?

Yes, it is started [here](https://github.com/sensepost/goDoH/blob/master/cmd/c2.go#L39). Maybe check that you don't have something like `systemd-resolve` using udp/53?

The only other thing I can think of is the configuration of the domain itself. Having an NS record for the subdomain pointing to your C2 should be enough to get it working.

**Comment by ManjuLalwani** [comment]
Thanks , yeah I did have. systemd-resolve using it up. fixed it and then
was able to have godoh on port 53.

netstat -nlp | grep ':53'

udp6       0      0 :::53                   :::*
    2656/./godoh

However, seeing new errors now like :
1. question had less than 9 labels , bailing.

This error is not consistent. If I re run it , the error disappears most of
the times.

The domain resolution also seems fine. have the NS record pointed to
subdomain and using the same for the agent & the server. I see my agent
hitting the doh provider - doing the 3 way HS & Push , Acks on https but
then nothing after that.On the server side , agent is still not registered.

Thanks,
Manju Lalwani

**Comment by leonjza** [comment]
> question had less than 9 labels , bailing.

This is not really an error, but rather the C2 saying that something tried to do a lookup that was not in the expected format (ie. had 9 labels seperated by `.`'s) [ref](https://github.com/sensepost/goDoH/blob/master/dnsserver/server.go#L292-L297). This often happens with Internet scanners and other things.

Assuming your DNS setup is fine, there is nothing else I can think of right now that could be the issue. I am confident with a proper setup the agent will check in fine having tested it again just this weekend.
