### ISSUE TITLE
Canonical repo address is inconsistent with go import path

### ISSUE THREAD

**Issue by KateGo520** [sensepost/godoh#5]
The github.com/sensepost/`godoh` repo was just renamed to github.com/sensepost/`goDoH`
This means that the canonical github repo address now conflicts with canonical go import packages (for example, `"github.com/sensepost/godoh/dnsclient"`, as referenced from https://github.com/sensepost/goDoH/blob/master/cmd/agent.go#L13)

It is now very easy for downstream consumers (which don't import "github.com/sensepost/godoh/..." packages) to accidentally clone and add imports to upper-case `"github.com/sensepost/goDoH/..."` packages. This will create many pitfalls and break the module users. They may encounter errors:
```
go: downloading github.com/sensepost/goDoH v0.0.0-20200517112203-e2bac6398fa7
go: github.com/sensepost/goDoH upgrade => v0.0.0-20200517112203-e2bac6398fa7
go get: github.com/sensepost/goDoH@v0.0.0-20200517112203-e2bac6398fa7: parsing go.mod:
        module declares its path as: github.com/sensepost/godoh
                but was required as: github.com/sensepost/goDoH
```

(This was possible before, but way harder to do accidentally, since all the links and clone commands from github agreed with the canonical go import packages)

Please consider reverting the `godoh` -> `goDoH` rename.

If the case change is here to stay, some things that would help a lot:
1) guidance and checks to ensure all the go repos under the org agree and continue to use `godoh`
2) example `go get` commands in the READMEs of all the go repos to guide consumers
3) add canonical import paths with the correct case (https://golang.org/doc/go1.4#canonicalimports) to prevent accidental use of the wrong case downstream

**Comment by KateGo520** [comment]
@leonjza  Could you help me review this issue? Thx :p

**Comment by leonjza** [comment]
Hey! The repo name has actually always been `goDoH`. However, it makes sense to get rid of the casing. Thanks for the heads up!

**Comment by leonjza** [comment]
Should be fine now. 👍

**Comment by KateGo520** [comment]
@leonjza Thank you for your contribution!
