### ISSUE TITLE
No agents registered Error

### ISSUE THREAD

**Issue by s4ksh1** [sensepost/godoh#9]
When I start c2 server, it is not checking for the agents and on running "agents" command it is giving a error "No agents registered". Any solution?

godoh -d IP c2      
INFO[0000] Using `google` as preferred provider         
INFO[0000] Using 10.36.146.78 as DNS domain             
Commands are directed to agents after switching to its context.

Use the `agents` command to list agents.
Use the `use agent-id` to interact with that agent and issue commands.
Use the `download path` in an agents' context to download files.
Use the `back` command to go back.

Current agent context: ``

c2> INFO[0000] DNS C2 starting...                            domain=10.36.146.78 module=c2

c2> agents
No agents registered.
c2>

**Comment by leonjza** [comment]
You need to have an agent registered for that to show any output. My first guess is its not based on the DNS domain in the output which is not a DNS domain but an IP address.

**Comment by s4ksh1** [comment]
What is the DNS domain?

**Comment by leonjza** [comment]
The domain where you C2 is hosted, where the DNS server runs and where agents will connect to. I recommend reading the blog post accompanied with this tool: https://sensepost.com/blog/2018/waiting-for-godoh/

**Comment by s4ksh1** [comment]
I have read this blog. There is a line written "Just like traditional DNS tunnelling, you would need to configure a domain (or subdomain) to have its name server point to your c2 server and run the godoh c2 command from there." I am wondering how would I configure a domain? Any help?

**Comment by leonjza** [comment]
Simply speaking, register a domain and point say a subdomains name server to your C2 server.
